### ISSUE TITLE
Mangojuice default config causing crash on vkcube

### ISSUE THREAD

**Issue by LethalManBoob** [radiolamp/mangojuice#18]
archlinux
goverlay default config works fine

**Comment by radiolamp** [comment]
> archlinux goverlay default config works fine

Can I please give an example, as I don't understand exactly what you are talking about, as there are no such parameters that could cause this.

**Comment by LethalManBoob** [comment]
I delete my mangohud.conf and boot mangojuice, save a custom config of any kind, it does not matter, then attempt to use mangohud with vkcube. it always will crash
goverlay works just fine if i save over it. i can repeat this test flawlessly

**Comment by radiolamp** [comment]
Is there a problem with your archlinux configuration or is there not enough information about the problem, do you have 2 video cards?

**Comment by LethalManBoob** [comment]
I am using 1 nvidia 3070 with arch/cachyos
https://github.com/user-attachments/assets/78a0cd68-3e30-4caa-8834-22a35b1d449e

**Comment by radiolamp** [comment]
> I am using 1 nvidia 3070 with arch/cachyos https://github.com/user-attachments/assets/78a0cd68-3e30-4caa-8834-22a35b1d449e

https://github.com/user-attachments/assets/78a0cd68-3e30-4caa-8834-22a35b1d449e bad

**Comment by LethalManBoob** [comment]
The issue is due to the default vsync settings
found out just now

**Comment by radiolamp** [comment]
added to the git version

**Comment by radiolamp** [comment]
please check if it is fixed in the new version.

**Comment by LethalManBoob** [comment]
Can confirm it now defaults to unset and works without issues
