### ISSUE TITLE
What feature are you missing the most right now?

### ISSUE THREAD

**Issue by radiolamp** [radiolamp/mangojuice#3]
Hello, I am the author of this program. At the moment the development of the functionality is actively underway, but I would like to know what you are missing most of all at the moment.

**Comment by radiolamp** [comment]
> Что-то, что не имело для меня смысла в Goverlay, так это настройка всей моей конфигурации, а затем необходимость вручную редактировать MangoHud.conf, потому что предустановки (SHIFT_R + F12 и т. д.), предлагаемые Goverlay, мне не подходили. Вариант "Custom", когда пользователь вручную вводит сочетание клавиш, был бы классным.

Are you interested in a certain key combination?

**Comment by radiolamp** [comment]
Если определённая то могу просто добавить в список, если она будет работать с mangohud

**Comment by slserg** [comment]
Добрый день.
Думаю что в планах у вас это было, но всё же напишу:
1. Выбор цвета для тех настроек где это возможно
2. Кнопка "Intel Power Fix" мне кажется должна быть во вкладке "Metrics", т.к. там есть соответствующей ей переключатель "CPU Power"
3. Заголовки групп выделить жирным шрифтом или как-то выделить

**Comment by LionHeartP** [comment]
Hello! 
I'm really liking this app and I already have it packaged on my copr, however it'd be great if you could implement these 2 features.

- no_display toggle
- Multiple fps limit steps.

For the second one, for example I set mine to 0,120,60,30 so I can toggle between these with shift+F1 on the fly.

Thanks again for this amazing app.

**Comment by slserg** [comment]
Т.к. установка vulkan-tools является опциональной, то рядом с кнопкой "Test" можно сделать значёк для всплывающей подсказкой о необходимости установки данного пакета. Или сделать проверку наличия пакета и если его нет при нажатии кнопки предупреждать о его отсутствии.

**Comment by radiolamp** [comment]
> Здравствуйте! Мне очень нравится это приложение, и оно уже установлено на моем Copr, однако было бы здорово, если бы вы могли реализовать эти 2 функции.
> 
> * no_display переключатель
> * Несколько шагов ограничения кадровой частоты.
> 
> Например, для второго я установил значения 0,120,60,30, чтобы можно было переключаться между ними «на лету» с помощью сочетания клавиш Shift+F1.
> 
> Еще раз спасибо за это замечательное приложение.

Очень интересное предложение, но это упирается в уже в работу самого mandohud и там нужно будет посмореть вожможно ли будет это сделать. Вообшем быстро не обещаю, так как занимаюсь этим проэктом после работы в свободное время, но если будет возмжность реализую

**Comment by slserg** [comment]
Не планируется добавить регулировку CAS из vkbasalt? Как было ранее в goverlay.

**Comment by slserg** [comment]
Хорошо бы добавить фикс (font_glyph_ranges = cyrillic) отображения кириллицы при включении Media

**Comment by radiolamp** [comment]
> Хорошо бы добавить фикс (font_glyph_ranges = cyrillic) отображения кириллицы при включении Media

добавил в гит версию

**Comment by slserg** [comment]
> > Хорошо бы добавить фикс (font_glyph_ranges = cyrillic) отображения кириллицы при включении Media
> 
> добавил в гит

В версии 0.6.5 aur изменений не нашел

**Comment by radiolamp** [comment]
> > > Хорошо бы добавить фикс (font_glyph_ranges = cyrillic) отображения кириллицы при включении Media
> > 
> > 
> > добавил в гит
> 
> В версии 0.6.5 aur изменений не нашел

попробуй изменить шрифты стандарный не поддерживает кирилицу как я понял

**Comment by slserg** [comment]
> > > > Хорошо бы добавить фикс (font_glyph_ranges = cyrillic) отображения кириллицы при включении Media
> > > 
> > > 
> > > добавил в гит
> > 
> > 
> > В версии 0.6.5 aur изменений не нашел
> 
> попробуй изменить шрифты стандарный не поддерживает кирилицу как я понял

Верно. Забыл про это.
С другим шрифтом всё отлично.
Спасибо

**Comment by slserg** [comment]
Не уверен что верно отформатированы надписи ARCH, Session.
![Снимок экрана от 2024-10-08 12-19-35](https://github.com/user-attachments/assets/29721f75-ff5d-492b-99b8-8d61f915f184)

**Comment by radiolamp** [comment]
> Не уверен что верно отформатированы надписи ARCH, Session. ![Снимок экрана от 2024-10-08 12-19-35](https://private-user-images.githubusercontent.com/183264918/374498532-29721f75-ff5d-492b-99b8-8d61f915f184.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODQ2MTcsIm5iZiI6MTcyODM4NDMxNywicGF0aCI6Ii8xODMyNjQ5MTgvMzc0NDk4NTMyLTI5NzIxZjc1LWZmNWQtNDkyYi05OWI4LThkNjFmOTE1ZjE4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxMDQ1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGY1OGEwMTEwMzY1NzdiYThiZmFmMjE2OThhOTYyNzBlNWZlZDgxZmI2YjM5YTI4NDQ0OGRkYjcyZjE4MDUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FeoiRP7kCezmlLEvOZJgEvgR7jY_isVc0yHX5xVvrd0)

Касаемо форматирование это в доработке на данный момент, вообще мангохуд позволяет выстраивать любой порядок, по этому сейчас думаю лучше оставить всё как в mangohud по умолчанию или всё же сделать больший закос под revo tuner с Windows например

**Comment by radiolamp** [comment]
просто на данный момент не так много времени на программу как хотелась бы, да и надо бы цвета доделать, хотя форматирование вроде как важнее.

**Comment by slserg** [comment]
Цвета сохраняются, но при следующем запуске программы сбрасываются на стандартные.
Intel power fix - может ли сохранятся после перезагрузки?

**Comment by radiolamp** [comment]
> Цвета сохраняются, но при следующем запуске программы сбрасываются на стандартные. Intel power fix - может ли сохранятся после перезагрузки?

Касаемо цвета то сегодня или завтра будет версия где будет считывая цвета из конфига, касаемо intel fix посмотрю

**Comment by slserg** [comment]
mangojuice 0.7.0 - Отлично!!! Great!!! Донат полетел. Так держать!!!
Немного не там себе представлял кнопки с цветами. Но это дело вкуса.
Буду рад если Intel fix заработает после перезагрузки.
Кнопочку "О приложении/About" сделать бы.

**Comment by slserg** [comment]
Выбор шрифта:
- может удобнее что бы по умолчанию открывался список на выбраном сейчас шрифте?
- прокрутка сейчас адаптируется под длину строку, не совсем удобно при просмотре (постоянно скачет ширина) и при перетаскивании бегунка нажатием мышки

**Comment by radiolamp** [comment]
Да буду доделывать, сейчас мне необходимо заняться рефакторингом кода и этот процесс необходим что бы в будущем было легче добавлять новые функции

**Comment by radiolamp** [comment]
> slserg

Так же большое спасибо за донат. Кстати думаю после рефакторинга создам группу скорее всего в телеграмме, есть ряд моментов которые требуют голосования. Например касаемо шрифтов и окна диалога, стандартный в гноме по крайней мере у меня он работает крайне медленно, если это всех устроит то можно и его внедрить, но можно доработать список и будет аля в говерлей или писать свой диалог, но дольше и таких моментов накопилась много. Например нужен ли перевод

**Comment by slserg** [comment]
0.7.1 - переключатель "Frame" при каждом открытии включен, даже если перед этим его выключить и сохранить.

**Comment by slserg** [comment]
"Vulcan driver" не показывает

**Comment by radiolamp** [comment]
> "Vulcan driver" не показывает

спасибо за информацию, протестирую, исправим

**Comment by radiolamp** [comment]
> "Vulcan driver" не показывает

похоже что сломан на стороне mangohud, в говер тоже не работат

**Comment by slserg** [comment]
> 0.7.1 - переключатель "Frame" при каждом открытии включен, даже если перед этим его выключить и сохранить.

Уточнение: переключатель включен, но не выводит данные. Чтобы он заработал, необходимо выключить и включить.
Стоит поправить некорректную работу.

**Comment by radiolamp** [comment]
> > 0.7.1 - переключатель "Frame" при каждом открытии включен, даже если перед этим его выключить и сохранить.
> 
> Уточнение: переключатель включен, но не выводит данные. Чтобы он заработал, необходимо выключить и включить. Стоит поправить некорректную работу.

это проблема уже исправлена в git версии, у тебя есть tg, мне бы не помешала помощь в тестирование перед релизом

**Comment by radiolamp** [comment]
> > 0.7.1 - переключатель "Frame" при каждом открытии включен, даже если перед этим его выключить и сохранить.
> 
> Уточнение: переключатель включен, но не выводит данные. Чтобы он заработал, необходимо выключить и включить. Стоит поправить некорректную работу.

https://t.me/+BLJ87zuc3C9jN2Ni
