### ISSUE TITLE
CPU Core Load and Core Bars

### ISSUE THREAD

**Issue by slserg** [radiolamp/mangojuice#4]
Since "CPU Core Bars" does not work without "CPU Core Load" enabled, it may be necessary to make it possible to activate "CPU Core Bars" only after activating "CPU Core Load"? Until then, it will not be active for changes.

**Comment by radiolamp** [comment]
The fact is that during development I was guided by the gowerway where this was not implemented; There are a number of switches that also require additional switches to be turned on. I will add this functionality to my implementation plans.
