### ISSUE TITLE
Unable to disable af and picmip

### ISSUE THREAD

**Issue by XNEP1** [radiolamp/mangojuice#5]
I was having graphical issues in a game while using mangohud. It turned out to be the fault of the af (Anisotropic filtering level) and picmip (Mip-map LoD bias) options.

In my MangoJuice GUI, I didn't intend to mess with these options, so I left them at the default (none and value set to 0).

Configured like this, MangoJuice will configure MangoHUD with the options
af=0
picmip=0

Which is not the same as these two settings not being set. The way to disable them is to not set any values ​​for these options, and it is not possible to do this in the current MangoJuice.

**Comment by radiolamp** [comment]
Thank you for the information. I have already added to the git version that if you do not touch the sliders, then there will be no values in the configuration
